import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/helpers/Navbar"
import ToasterContext from "@/components/ToastContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-900 text-white`}
      >
        <div className="fixed inset-0 w-full h-full -z-10 overflow-hidden">
          <div className="wave">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div className="relative">
          <ToasterContext />

          <Navbar />
        </div>

        <main className="relative ">
          {children}
        </main>
      </body>
    </html>
  );
}
